WA_Apprendo/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WA_Apprendo.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AdministrarAlumnos()
        {
            return View();
        }

    }
}

WA_Apprendo/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WA_Apprendo.Models;

namespace WA_Apprendo.Controllers
{
    public class ClienteController : Controller
    {

        ApprendoEntities model = new ApprendoEntities();

        // GET: Cliente
        public ActionResult MiPerfil()
        {
            return View();
        }

        public ActionResult Mantenimiento()
        {
            return View();
        }
    }
}

WA_Apprendo/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WA_Apprendo.Controllers
{
    public class CursoController : Controller
    {
        // GET: Curso
        public ActionResult Mantenimiento()
        {
            return View();
        }
    }
}

WA_Apprendo/Controllers/ReservaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WA_Apprendo.Controllers
{
    public class ReservaController : Controller
    {

        // GET: Horario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ReservasProfesor()
        {
            return View();
        }

    }
}

WA_Apprendo/Views/Shared/MenuAdministrador.cshtml
<div class="bg-light border-right " id="sidebar-wrapper">
    <div class="sidebar-heading "><img class="apprendo" src="~/images/Apprendo.png" /> </div>
    <div class="list-group list-group-flush">
        <a href="@Url.Action("Dashboard", "Administrador")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-calendar-day"></i> Dashboard</a>
        <a href="@Url.Action("Finanzas","Administrador")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-dollar-sign"></i>  Finanzas</a>
        <a href="@Url.Action("Mantenimiento", "Curso")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-book"></i> Cursos</a>
        <a href="@Url.Action("Mantenimiento", "Cliente")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-users"></i> Clientes</a>
        <a href="@Url.Action("Mantenimiento", "Profesor")" class="list-group-item list-group-item-action bg-light"><i class="fas fa-chalkboard-teacher"></i> Profesores</a>

        <br>
        <br>

        <a href="#" class="list-group-item list-group-item-action bg-light"><i class="fa fa-sign-out-alt"></i> Cerrar sesión</a>
        <br>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>

WA_Apprendo/Views/Shared/MenuCliente.cshtml
<div class="bg-light border-right " id="sidebar-wrapper">
    <div class="sidebar-heading "><img class="apprendo" src="~/images/Apprendo.png" /> </div>
    <div class="list-group list-group-flush">
        <a href='@Url.Action("Index", "Reserva")' class="list-group-item list-group-item-action bg-light"><i class="fa fa-calendar-day"></i> Reservar clase</a>

        <a href="@Url.Action("AdministrarAlumnos","Alumno")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-child"></i> Administrar alummnos</a>
        <a href="#" class="list-group-item list-group-item-action bg-light"><i class="fa fa-chalkboard"></i> Mis clases reservadas</a>
        <a href="@Url.Action("MiPerfil", "Cliente")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-address-card"></i> Mi Perfil</a>
        <br>
        <br>
        <a href="#" class="list-group-item list-group-item-action bg-light"><i class="fa fa-sign-out-alt"></i> Cerrar sesión</a>
        <a href="#" class="list-group-item list-group-item-action bg-light"><i class="fa fa-key"></i> Cambiar contraseña</a>
        <br>
    </div>
</div>

WA_Apprendo/Views/Shared/MenuProfesor.cshtml
<div class="bg-light border-right " id="sidebar-wrapper">
    <div class="sidebar-heading "><img class="apprendo" src="~/images/Apprendo.png" /> </div>
    <div class="list-group list-group-flush">
        <a href="@Url.Action("ClasesProfesor", "Profesor")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-calendar-day"></i> Mis clases</a>
        <a href="@Url.Action("ReservaProfesor", "Profesor")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-calendar-day"></i> Mis reservas</a>
        <a href="@Url.Action("GananciasProfesor", "Profesor")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-calendar-day"></i> Mis ingresos</a>
        <a href="@Url.Action("MiPerfil", "Profesor")" class="list-group-item list-group-item-action bg-light"><i class="fa fa-address-card"></i> Mi perfil</a>
        <br>
        <br>
        <a href="#" class="list-group-item list-group-item-action bg-light"><i class="fa fa-sign-out-alt"></i> Cerrar sesión</a>
        <a href="#" class="list-group-item list-group-item-action bg-light"><i class="fa fa-key"></i> Cambiar contraseña</a>
        <br>
    </div>
</div>

WA_Apprendo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>

    <link href="~/css/navEstilos.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />
    <link href="~/css/dash.css" rel="stylesheet" />

    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/solid.css" integrity="sha384-QokYePQSOwpBDuhlHOsX0ymF6R/vLk/UQVz3WHa6wygxI5oGTmDTv8wahFOSspdm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/fontawesome.css" integrity="sha384-vd1e11sR28tEK9YANUtpIOdjGW14pS87bUBuOIoBILVWLFnS+MCX9T6MMf0VdPGq" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>

</head>

<body>


    @RenderBody()

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Scripts/main.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>